import React, { useCallback, useEffect, useState } from "react";
import {
  Table,
  TableHeader,
  TableColumn,
  TableBody,
  TableRow,
  TableCell,
  Input,
  Button,
  DropdownTrigger,
  Dropdown,
  DropdownMenu,
  DropdownItem,
  Pagination,
  useDisclosure,
  Modal,
  ModalContent,
  ModalHeader,
  ModalBody,
  ModalFooter,
  Textarea,
  addToast,
  Select,
  SelectItem,
} from "@heroui/react";
import { ChevronDown, EllipsisVertical, Plus, Search } from "lucide-react";
import { useDispatch, useSelector } from "react-redux";
import {
  addMileStoneInProduct,
  createMileStone,
  deleteMileStoneInProduct,
  getAllMilestones,
  getProductMileStonesListByProductId,
  updateMilestoneInProduct,
} from "../../toolkit/slices/operationSlice";
import { zodResolver } from "@hookform/resolvers/zod";
import { Controller, useForm } from "react-hook-form";
import * as z from "zod";
import { useMediaQuery } from "react-responsive";
import { getAllDepartment } from "../../toolkit/slices/settingSlice";
import NewSelect from "../../components/NewSelect";
import { useParams } from "react-router-dom";

export const columns = [
  { name: "ID", uid: "id" },
  { name: "NAME", uid: "milestoneName", sortable: true },
  { name: "ORDER", uid: "order" },
  { name: "TAT", uid: "tatInDays" },
  { name: "ROLLBACK TAT", uid: "rollbackTatInDays" },
  { name: "MAX ATTEMPTS", uid: "maxAttempts" },
  { name: "PAYMENT %", uid: "paymentPercentage" },
  { name: "STRICT APPROVAL", uid: "strictApproval" },
  { name: "MANDATORY", uid: "mandatory" },
  { name: "AUTO GENERATED", uid: "autoGenerated" },
  { name: "ALLOW ROLLBACK", uid: "allowRollback" },
  { name: "ACTIONS", uid: "actions" },
];

export function capitalize(s) {
  return s ? s.charAt(0).toUpperCase() + s.slice(1).toLowerCase() : "";
}

const INITIAL_VISIBLE_COLUMNS = [
  "milestoneName",
  "order",
  "tatInDays",
  "rollbackTatInDays",
  "maxAttempts",
  "paymentPercentage",
  "strictApproval",
  "mandatory",
  "autoGenerated",
  "allowRollback",
  "actions",
];

const formSchema = z.object({
  milestoneId: z.string().min(1, "Please select milestone name."),
  tatInDays: z.string().min(1, "Please enter tat in days."),
  order: z.string().min(1, "Please enter order"),
  rollbackTatInDays: z.string().min(1, "Please enter roll back tat in days."),
  strictApproval: z.boolean(),
  allowRollback: z.boolean(),
  maxAttempts: z.string().min(1, "Please enter max attempts."),
  paymentPercentage: z.string().min(1, "Please enter payment percentage."),
  autoGenerated: z.boolean(),
  mandatory: z.boolean(),
});

const defaultValues = {
  milestoneId: "",
  tatInDays: "",
  order: "",
  rollbackTatInDays: "",
  strictApproval: false,
  allowRollback: false,
  maxAttempts: "",
  paymentPercentage: "",
  autoGenerated: false,
  mandatory: false,
};

const ProductMilestones = ({ details }) => {
  const { userId, solutionId } = useParams();
  const dispatch = useDispatch();
  const { isOpen, onClose, onOpen, onOpenChange } = useDisclosure();
  const deleteModal = useDisclosure();
  const data = useSelector((state) => state.operation.productMileStoneList);
  const mileStoneList = useSelector((state) => state.operation.mileStoneList);
  const [filterValue, setFilterValue] = React.useState("");
  const [visibleColumns, setVisibleColumns] = React.useState(
    new Set(INITIAL_VISIBLE_COLUMNS)
  );

  const [sortDescriptor, setSortDescriptor] = React.useState({
    column: "name",
    direction: "ascending",
  });
  const [rowItem, setRowItem] = useState(null);
  const hasSearchFilter = Boolean(filterValue);
  const isMedium = useMediaQuery({ minWidth: 768, maxWidth: 1535 });
  const isLarge = useMediaQuery({ minWidth: 1536 });

  useEffect(() => {
    dispatch(getProductMileStonesListByProductId({ userId, productId:solutionId }));
    dispatch(getAllMilestones());
  }, [dispatch]);

  const headerColumns = React.useMemo(() => {
    if (visibleColumns === "all") return columns;

    return columns.filter((column) =>
      Array.from(visibleColumns).includes(column.uid)
    );
  }, [visibleColumns]);

  const filteredItems = React.useMemo(() => {
    let filteredUsers = [...(data || [])];

    if (hasSearchFilter) {
      filteredUsers = filteredUsers.filter((item) =>
        Object.values(item)?.some((val) =>
          String(val)?.toLowerCase().includes(filterValue.toLowerCase())
        )
      );
    }

    return filteredUsers;
  }, [data, filterValue]);

  const sortedItems = React.useMemo(() => {
    return [...filteredItems].sort((a, b) => {
      const first = a[sortDescriptor.column];
      const second = b[sortDescriptor.column];
      const cmp = first < second ? -1 : first > second ? 1 : 0;

      return sortDescriptor.direction === "descending" ? -cmp : cmp;
    });
  }, [sortDescriptor, filteredItems]);

  const {
    control,
    handleSubmit,
    formState: { errors },
    reset,
  } = useForm({
    resolver: zodResolver(formSchema),
    defaultValues,
  });

  const handleActionsPress = (type, rowData) => {
    if (type === "edit") {
      reset({
        milestoneId: String(rowData?.milestoneId),
        tatInDays: String(rowData?.tatInDays),
        order: String(rowData?.order),
        rollbackTatInDays: String(rowData?.rollbackTatInDays),
        strictApproval: rowData?.strictApproval,
        allowRollback: rowData?.allowRollback,
        maxAttempts: String(rowData?.maxAttempts),
        paymentPercentage: String(rowData?.paymentPercentage),
        autoGenerated: rowData?.autoGenerated,
        mandatory: rowData?.mandatory,
      });
      onOpen();
    } else {
      deleteModal.onOpen();
    }
    setRowItem(rowData);
  };

  const handleDeleteMileStone = () => {
    dispatch(deleteMileStoneInProduct(rowItem?.id))
      .then((resp) => {
        if (resp.meta.requestStatus === "fulfilled") {
          addToast({
            title: "Milestone deleted successfully !.",
            color: "success",
          });
          dispatch(getProductMileStonesListByProductId({ userId, productId:solutionId }));
          setRowItem(null);
          deleteModal.onClose();
        } else {
          addToast({ title: "Something went wrong !.", color: "danger" });
        }
      })
      .catch(() => {
        addToast({ title: "Something went wrong !.", color: "danger" });
      });
  };

  const renderCell = React.useCallback((rowData, columnKey) => {
    const cellValue = rowData[columnKey];
    switch (columnKey) {
      case "milestoneName":
        return <p>{rowData?.milestoneName} </p>;
      case "tatInDays":
        return <p>{rowData?.tatInDays} days </p>;
      case "rollbackTatInDays":
        return <p>{rowData?.rollbackTatInDays} days </p>;
      case "strictApproval":
        return <p>{rowData?.strictApproval ? "YES" : "NO"}</p>;
      case "mandatory":
        return <p>{rowData?.mandatory ? "YES" : "NO"}</p>;
      case "autoGenerated":
        return <p>{rowData?.autoGenerated ? "YES" : "NO"}</p>;
      case "allowRollback":
        return <p>{rowData?.allowRollback ? "YES" : "NO"}</p>;
      case "actions":
        return (
          <div className="relative flex justify-center items-center gap-2">
            <Dropdown>
              <DropdownTrigger>
                <Button isIconOnly size="sm" variant="light">
                  <EllipsisVertical />
                </Button>
              </DropdownTrigger>
              <DropdownMenu>
                <DropdownItem
                  key="edit"
                  onPress={() => handleActionsPress("edit", rowData)}
                >
                  Edit
                </DropdownItem>
                <DropdownItem
                  key="delete"
                  color="danger"
                  onPress={() => handleActionsPress("delete", rowData)}
                >
                  Delete
                </DropdownItem>
              </DropdownMenu>
            </Dropdown>
          </div>
        );
      default:
        return cellValue;
    }
  }, []);

  const onSearchChange = React.useCallback((value) => {
    if (value) {
      setFilterValue(value);
    } else {
      setFilterValue("");
    }
  }, []);

  const onClear = React.useCallback(() => {
    setFilterValue("");
  }, []);

  const onSubmit = useCallback(
    (values) => {
      const obj = {
        ...values,
        productId:solutionId,
      };
      if (rowItem) {
        dispatch(updateMilestoneInProduct({ id: rowItem?.id, data: obj }))
          .then((resp) => {
            if (resp.meta.requestStatus === "fulfilled") {
              addToast({
                title: "Milestone updated successfully !.",
                color: "success",
              });
              dispatch(
                getProductMileStonesListByProductId({ userId, productId:solutionId })
              );
              onClose();
              setRowItem(null);
              reset(defaultValues);
            } else {
              addToast({ title: "Something went wrong !.", color: "danger" });
            }
          })
          .catch(() =>
            addToast({ title: "Something went wrong !.", color: "danger" })
          );
      } else {
        dispatch(addMileStoneInProduct(obj))
          .then((resp) => {
            if (resp.meta.requestStatus === "fulfilled") {
              addToast({
                title: "Milestone mapped with product successfully !.",
                color: "success",
              });
              dispatch(
                getProductMileStonesListByProductId({ userId, productId:solutionId })
              );
              onClose();
              reset(defaultValues);
            } else {
              addToast({ title: "Something went wrong !.", color: "danger" });
            }
          })
          .catch(() =>
            addToast({ title: "Something went wrong !.", color: "danger" })
          );
      }
    },
    [dispatch, onClose, reset, userId, solutionId, rowItem]
  );

  const topContent = React.useMemo(() => {
    return (
      <div className="flex flex-col gap-4 mb-1">
        <div className="flex justify-between gap-3 items-end">
          <Input
            isClearable
            className="w-full sm:max-w-[35%]"
            placeholder="Search..."
            startContent={<Search />}
            value={filterValue}
            onClear={() => onClear()}
            onValueChange={onSearchChange}
          />
          <div className="flex gap-3">
            <Button
              endContent={<Plus />}
              color="primary"
              onPress={onOpen}
              size={isMedium ? "sm" : isLarge ? "md" : ""}
            >
              Map milestone
            </Button>
            <Dropdown>
              <DropdownTrigger>
                <Button endContent={<ChevronDown />} variant="flat">
                  Columns
                </Button>
              </DropdownTrigger>
              <DropdownMenu
                disallowEmptySelection
                aria-label="Table Columns"
                closeOnSelect={false}
                selectedKeys={visibleColumns}
                selectionMode="multiple"
                onSelectionChange={setVisibleColumns}
              >
                {columns.map((column) => (
                  <DropdownItem key={column.uid} className="capitalize">
                    {capitalize(column.name)}
                  </DropdownItem>
                ))}
              </DropdownMenu>
            </Dropdown>
          </div>
        </div>
      </div>
    );
  }, [filterValue, visibleColumns, onSearchChange, hasSearchFilter]);

  return (
    <>
      <h1 className="font-sans text-2xl font-medium mb-1">Milestones list</h1>
      <Table
        isHeaderSticky
        aria-label="Example table with custom cells, pagination and sorting"
        bottomContentPlacement="outside"
        classNames={{
          wrapper: "max-h-[55vh] w-full",
          table: "w-full",
        }}
        sortDescriptor={sortDescriptor}
        topContent={topContent}
        topContentPlacement="outside"
        onSortChange={setSortDescriptor}
      >
        <TableHeader columns={headerColumns}>
          {(column) => (
            <TableColumn
              key={column.uid}
              align={column.uid === "actions" ? "center" : "start"}
              allowsSorting={column.sortable}
            >
              {column.name}
            </TableColumn>
          )}
        </TableHeader>
        <TableBody emptyContent={"No data found"} items={sortedItems}>
          {(item) => (
            <TableRow key={item.id}>
              {(columnKey) => (
                <TableCell>{renderCell(item, columnKey)}</TableCell>
              )}
            </TableRow>
          )}
        </TableBody>
      </Table>
      <Modal
        size="2xl"
        isDismissable={false}
        isKeyboardDismissDisabled={true}
        isOpen={isOpen}
        onOpenChange={onOpenChange}
        placement="top-center"
      >
        <ModalContent>
          {(onClose) => (
            <>
              <ModalHeader>
                {rowItem ? "Update milestone" : "Add milestone"}
              </ModalHeader>
              <ModalBody>
                <form onSubmit={handleSubmit(onSubmit)}>
                  <div className="grid grid-cols-2 gap-4 max-h-[60vh] overflow-auto">
                    <Controller
                      name="milestoneId"
                      control={control}
                      defaultValue={[]}
                      render={({ field }) => (
                        <NewSelect
                          isRequired={true}
                          data={mileStoneList || []}
                          label={"Select milestone"}
                          name={"milestoneId"}
                          labelKey={"name"}
                          valueKey={"id"}
                          value={field.value}
                          onChange={(selectedSet) => {
                            field.onChange(selectedSet);
                          }}
                        />
                      )}
                    />
                    <Controller
                      name="tatInDays"
                      control={control}
                      render={({ field }) => (
                        <Input
                          isRequired
                          label="TAT (in days)"
                          name="tatInDays"
                          value={field.value}
                          onChange={(e) => {
                            field.onChange(e.target.value);
                          }}
                        />
                      )}
                    />
                    <Controller
                      name="order"
                      control={control}
                      render={({ field }) => (
                        <Input
                          isRequired
                          label="Order"
                          name="order"
                          value={field.value}
                          onChange={(e) => {
                            field.onChange(e.target.value);
                          }}
                        />
                      )}
                    />
                    <Controller
                      name="rollbackTatInDays"
                      control={control}
                      render={({ field }) => (
                        <Input
                          isRequired
                          label="Roll back TAT (in days)"
                          name="rollbackTatInDays"
                          value={field.value}
                          onChange={(e) => {
                            field.onChange(e.target.value);
                          }}
                        />
                      )}
                    />

                    <Controller
                      name="strictApproval"
                      control={control}
                      render={({ field, fieldState: { error } }) => (
                        <Select
                          label="Strict approval"
                          isRequired
                          size={isMedium ? "sm" : isLarge ? "md" : ""}
                          selectedKeys={
                            field.value !== undefined
                              ? [field.value.toString()]
                              : []
                          }
                          onSelectionChange={(keys) => {
                            const value = Array.from(keys)[0];
                            if (value !== undefined)
                              field.onChange(value === "true");
                          }}
                          errorMessage={error?.message}
                          isInvalid={!!error}
                        >
                          {[
                            { label: "YES", value: true },
                            { label: "NO", value: false },
                          ].map((item) => (
                            <SelectItem
                              key={item.value.toString()}
                              value={item.value}
                            >
                              {item.label}
                            </SelectItem>
                          ))}
                        </Select>
                      )}
                    />
                    <Controller
                      name="allowRollback"
                      control={control}
                      render={({ field, fieldState: { error } }) => (
                        <Select
                          label="Allow roll back"
                          isRequired
                          size={isMedium ? "sm" : isLarge ? "md" : ""}
                          selectedKeys={
                            field.value !== undefined
                              ? [field.value.toString()]
                              : []
                          }
                          onSelectionChange={(keys) => {
                            const value = Array.from(keys)[0];
                            if (value !== undefined)
                              field.onChange(value === "true");
                          }}
                          errorMessage={error?.message}
                          isInvalid={!!error}
                        >
                          {[
                            { label: "YES", value: true },
                            { label: "NO", value: false },
                          ].map((item) => (
                            <SelectItem
                              key={item.value.toString()}
                              value={item.value}
                            >
                              {item.label}
                            </SelectItem>
                          ))}
                        </Select>
                      )}
                    />

                    <Controller
                      name="maxAttempts"
                      control={control}
                      render={({ field }) => (
                        <Input
                          isRequired
                          label="Max attempts"
                          name="maxAttempts"
                          value={field.value}
                          onChange={(e) => {
                            field.onChange(e.target.value);
                          }}
                        />
                      )}
                    />

                    <Controller
                      name="paymentPercentage"
                      control={control}
                      render={({ field }) => (
                        <Input
                          isRequired
                          label="Payment percentage"
                          name="paymentPercentage"
                          value={field.value}
                          onChange={(e) => {
                            field.onChange(e.target.value);
                          }}
                        />
                      )}
                    />

                    <Controller
                      name="autoGenerated"
                      control={control}
                      render={({ field, fieldState: { error } }) => (
                        <Select
                          label="Auto genrate"
                          isRequired
                          size={isMedium ? "sm" : isLarge ? "md" : ""}
                          selectedKeys={
                            field.value !== undefined
                              ? [field.value.toString()]
                              : []
                          }
                          onSelectionChange={(keys) => {
                            const value = Array.from(keys)[0];
                            if (value !== undefined)
                              field.onChange(value === "true");
                          }}
                          errorMessage={error?.message}
                          isInvalid={!!error}
                        >
                          {[
                            { label: "YES", value: true },
                            { label: "NO", value: false },
                          ].map((item) => (
                            <SelectItem
                              key={item.value.toString()}
                              value={item.value}
                            >
                              {item.label}
                            </SelectItem>
                          ))}
                        </Select>
                      )}
                    />
                    <Controller
                      name="mandatory"
                      control={control}
                      render={({ field, fieldState: { error } }) => (
                        <Select
                          label="Mandatory"
                          isRequired
                          size={isMedium ? "sm" : isLarge ? "md" : ""}
                          selectedKeys={
                            field.value !== undefined
                              ? [field.value.toString()]
                              : []
                          }
                          onSelectionChange={(keys) => {
                            const value = Array.from(keys)[0];
                            if (value !== undefined)
                              field.onChange(value === "true");
                          }}
                          errorMessage={error?.message}
                          isInvalid={!!error}
                        >
                          {[
                            { label: "YES", value: true },
                            { label: "NO", value: false },
                          ].map((item) => (
                            <SelectItem
                              key={item.value.toString()}
                              value={item.value}
                            >
                              {item.label}
                            </SelectItem>
                          ))}
                        </Select>
                      )}
                    />
                  </div>
                  <ModalFooter className="flex justify-end">
                    <Button onPress={onClose}>Cancel</Button>
                    <Button color="primary" type="submit">
                      Submit
                    </Button>
                  </ModalFooter>
                </form>
              </ModalBody>
            </>
          )}
        </ModalContent>
      </Modal>
      <Modal
        isOpen={deleteModal.isOpen}
        onOpenChange={deleteModal.onOpenChange}
        backdrop="blur"
      >
        <ModalContent>
          {(onClose) => (
            <>
              <ModalHeader className="flex flex-col gap-1">Delete</ModalHeader>
              <ModalBody>
                <p>Are you sure to delete this item ?</p>
              </ModalBody>
              <ModalFooter>
                <Button onPress={onClose}>No</Button>
                <Button color="primary" onPress={handleDeleteMileStone}>
                  Yes
                </Button>
              </ModalFooter>
            </>
          )}
        </ModalContent>
      </Modal>
    </>
  );
};

export default ProductMilestones;
