import React, { useCallback, useEffect, useState } from "react";
import {
  Table,
  TableHeader,
  TableColumn,
  TableBody,
  TableRow,
  TableCell,
  Input,
  Button,
  DropdownTrigger,
  Dropdown,
  DropdownMenu,
  DropdownItem,
  useDisclosure,
  Modal,
  ModalContent,
  ModalHeader,
  ModalBody,
  ModalFooter,
  addToast,
  Select,
  SelectItem,
} from "@heroui/react";
import { ChevronDown, EllipsisVertical, Plus, Search } from "lucide-react";
import { useDispatch, useSelector } from "react-redux";
import {
  addMileStoneInProduct,
  deleteMileStoneInProduct,
  getAllMilestones,
  getProductMileStonesListByProductId,
  updateMilestoneInProduct,
} from "../../toolkit/slices/operationSlice";
import { zodResolver } from "@hookform/resolvers/zod";
import { Controller, useForm } from "react-hook-form";
import * as z from "zod";
import { useMediaQuery } from "react-responsive";
import NewSelect from "../../components/NewSelect";
import { useParams } from "react-router-dom";

export const columns = [
  { name: "ID", uid: "id" },
  { name: "NAME", uid: "milestoneName" },
  { name: "ORDER", uid: "order" },
  { name: "TAT", uid: "tatInDays" },
  { name: "ROLLBACK TAT", uid: "rollbackTatInDays" },
  { name: "MAX ATTEMPTS", uid: "maxAttempts" },
  { name: "PAYMENT %", uid: "paymentPercentage" },
  { name: "STRICT APPROVAL", uid: "strictApproval" },
  { name: "MANDATORY", uid: "mandatory" },
  { name: "AUTO GENERATED", uid: "autoGenerated" },
  { name: "ALLOW ROLLBACK", uid: "allowRollback" },
  { name: "ACTIONS", uid: "actions" },
];

export function capitalize(s) {
  return s ? s.charAt(0).toUpperCase() + s.slice(1).toLowerCase() : "";
}

const INITIAL_VISIBLE_COLUMNS = [
  "milestoneName",
  "order",
  "tatInDays",
  "rollbackTatInDays",
  "maxAttempts",
  "paymentPercentage",
  "strictApproval",
  "mandatory",
  "autoGenerated",
  "allowRollback",
  "actions",
];

const requiredString = (message) => z.string().min(1, message);

const formSchema = z.object({
  milestoneId: requiredString("Please select milestone name."),
  order: requiredString("Please enter order."),

  tatInDays: requiredString("Please enter TAT in days."),

  executionTatApplicable: z.boolean(),
  executionTatInDays: requiredString("Please enter execution TAT in days."),
  executionTatHours: requiredString("Please enter execution TAT hours."),

  departmentTatApplicable: z.boolean(),
  departmentTatHours: requiredString("Please enter department TAT hours."),

  performanceTatApplicable: z.boolean(),
  performanceTatHours: requiredString("Please enter performance TAT hours."),

  customerTatApplicable: z.boolean(),
  customerTatHours: requiredString("Please enter customer TAT hours."),

  rollbackTatApplicable: z.boolean(),
  rollbackTatInDays: requiredString("Please enter rollback TAT in days."),
  rollbackTatHours: requiredString("Please enter rollback TAT hours."),

  strictApproval: z.boolean(),
  allowRollback: z.boolean(),

  maxAttempts: requiredString("Please enter max attempts."),
  paymentPercentage: requiredString("Please enter payment percentage."),

  requiresPortalDetails: z.boolean(),
  allowTatResetOnReassign: z.boolean(),
  businessDaysEnabled: z.boolean(),

  reminderBeforeDueHours: requiredString("Please enter reminder hours."),
  managerEscalationAfterDueHours: requiredString(
    "Please enter manager escalation hours.",
  ),
  hodEscalationAfterDueHours: requiredString(
    "Please enter HOD escalation hours.",
  ),

  mandatory: z.boolean(),
  active: z.boolean(),
  autoGenerated: z.boolean(),
});

const defaultValues = {
  milestoneId: "",
  order: "",

  tatInDays: "",

  executionTatApplicable: true,
  executionTatInDays: "0",
  executionTatHours: "0",

  departmentTatApplicable: true,
  departmentTatHours: "0",

  performanceTatApplicable: true,
  performanceTatHours: "0",

  customerTatApplicable: true,
  customerTatHours: "0",

  rollbackTatApplicable: true,
  rollbackTatInDays: "",
  rollbackTatHours: "0",

  strictApproval: false,
  allowRollback: true,

  maxAttempts: "",
  paymentPercentage: "100",

  requiresPortalDetails: true,
  allowTatResetOnReassign: true,
  businessDaysEnabled: true,

  reminderBeforeDueHours: "0",
  managerEscalationAfterDueHours: "0",
  hodEscalationAfterDueHours: "0",

  mandatory: true,
  active: true,
  autoGenerated: false,
};

const toNumber = (value, fallback = 0) => {
  const numberValue = Number(value);
  return Number.isFinite(numberValue) ? numberValue : fallback;
};

const getStringValue = (value, fallback = "") => {
  if (value === null || value === undefined) return fallback;
  return String(value);
};

const getBooleanValue = (value, fallback = false) => {
  if (value === null || value === undefined) return fallback;
  return Boolean(value);
};

const ProductMilestones = ({ details }) => {
  const { userId, solutionId } = useParams();
  const dispatch = useDispatch();

  const { isOpen, onClose, onOpen, onOpenChange } = useDisclosure();
  const deleteModal = useDisclosure();

  const data = useSelector((state) => state.operation.productMileStoneList);
  const mileStoneList = useSelector((state) => state.operation.mileStoneList);

  const [filterValue, setFilterValue] = React.useState("");
  const [visibleColumns, setVisibleColumns] = React.useState(
    new Set(INITIAL_VISIBLE_COLUMNS),
  );

  const [sortDescriptor, setSortDescriptor] = React.useState({
    column: "name",
    direction: "ascending",
  });

  const [rowItem, setRowItem] = useState(null);

  const hasSearchFilter = Boolean(filterValue);
  const isMedium = useMediaQuery({ minWidth: 768, maxWidth: 1535 });
  const isLarge = useMediaQuery({ minWidth: 1536 });

  const {
    control,
    handleSubmit,
    formState: { errors },
    reset,
  } = useForm({
    resolver: zodResolver(formSchema),
    defaultValues,
  });

  useEffect(() => {
    dispatch(
      getProductMileStonesListByProductId({ userId, productId: solutionId }),
    );
    dispatch(getAllMilestones());
  }, [dispatch, userId, solutionId]);

  const headerColumns = React.useMemo(() => {
    if (visibleColumns === "all") return columns;

    return columns.filter((column) =>
      Array.from(visibleColumns).includes(column.uid),
    );
  }, [visibleColumns]);

  const filteredItems = React.useMemo(() => {
    let filteredUsers = [...(data || [])];

    if (hasSearchFilter) {
      filteredUsers = filteredUsers.filter((item) =>
        Object.values(item)?.some((val) =>
          String(val)?.toLowerCase().includes(filterValue.toLowerCase()),
        ),
      );
    }

    return filteredUsers;
  }, [data, filterValue, hasSearchFilter]);

  const sortedItems = React.useMemo(() => {
    return [...filteredItems];
  }, [sortDescriptor, filteredItems]);

  const renderNumberInput = (name, label) => (
    <Controller
      name={name}
      control={control}
      render={({ field, fieldState: { error } }) => (
        <Input
          isRequired
          type="number"
          label={label}
          name={name}
          value={field.value}
          onChange={(e) => field.onChange(e.target.value)}
          errorMessage={error?.message}
          isInvalid={!!error}
          size={isMedium ? "sm" : isLarge ? "md" : ""}
        />
      )}
    />
  );

  const renderBooleanSelect = (name, label) => (
    <Controller
      name={name}
      control={control}
      render={({ field, fieldState: { error } }) => (
        <Select
          label={label}
          isRequired
          size={isMedium ? "sm" : isLarge ? "md" : ""}
          selectedKeys={
            field.value !== undefined ? [field.value.toString()] : []
          }
          onSelectionChange={(keys) => {
            const value = Array.from(keys)[0];
            if (value !== undefined) {
              field.onChange(value === "true");
            }
          }}
          errorMessage={error?.message}
          isInvalid={!!error}
        >
          {[
            { label: "YES", value: true },
            { label: "NO", value: false },
          ].map((item) => (
            <SelectItem key={item.value.toString()} value={item.value}>
              {item.label}
            </SelectItem>
          ))}
        </Select>
      )}
    />
  );

  const handleOpenAddModal = () => {
    setRowItem(null);
    reset(defaultValues);
    onOpen();
  };

  const handleActionsPress = (type, rowData) => {
    if (type === "edit") {
      reset({
        milestoneId: getStringValue(rowData?.milestoneId),
        order: getStringValue(rowData?.order),

        tatInDays: getStringValue(rowData?.tatInDays),

        executionTatApplicable: getBooleanValue(
          rowData?.executionTatApplicable,
          true,
        ),
        executionTatInDays: getStringValue(rowData?.executionTatInDays, "0"),
        executionTatHours: getStringValue(rowData?.executionTatHours, "0"),

        departmentTatApplicable: getBooleanValue(
          rowData?.departmentTatApplicable,
          true,
        ),
        departmentTatHours: getStringValue(rowData?.departmentTatHours, "0"),

        performanceTatApplicable: getBooleanValue(
          rowData?.performanceTatApplicable,
          true,
        ),
        performanceTatHours: getStringValue(rowData?.performanceTatHours, "0"),

        customerTatApplicable: getBooleanValue(
          rowData?.customerTatApplicable,
          true,
        ),
        customerTatHours: getStringValue(rowData?.customerTatHours, "0"),

        rollbackTatApplicable: getBooleanValue(
          rowData?.rollbackTatApplicable,
          true,
        ),
        rollbackTatInDays: getStringValue(rowData?.rollbackTatInDays),
        rollbackTatHours: getStringValue(rowData?.rollbackTatHours, "0"),

        strictApproval: getBooleanValue(rowData?.strictApproval, false),
        allowRollback: getBooleanValue(rowData?.allowRollback, true),

        maxAttempts: getStringValue(rowData?.maxAttempts),
        paymentPercentage: getStringValue(rowData?.paymentPercentage, "100"),

        requiresPortalDetails: getBooleanValue(
          rowData?.requiresPortalDetails,
          true,
        ),
        allowTatResetOnReassign: getBooleanValue(
          rowData?.allowTatResetOnReassign,
          true,
        ),
        businessDaysEnabled: getBooleanValue(
          rowData?.businessDaysEnabled,
          true,
        ),

        reminderBeforeDueHours: getStringValue(
          rowData?.reminderBeforeDueHours,
          "0",
        ),
        managerEscalationAfterDueHours: getStringValue(
          rowData?.managerEscalationAfterDueHours,
          "0",
        ),
        hodEscalationAfterDueHours: getStringValue(
          rowData?.hodEscalationAfterDueHours,
          "0",
        ),

        mandatory: getBooleanValue(rowData?.mandatory, true),
        active: getBooleanValue(rowData?.active, true),
        autoGenerated: getBooleanValue(rowData?.autoGenerated, false),
      });

      onOpen();
    } else {
      deleteModal.onOpen();
    }

    setRowItem(rowData);
  };

  const handleDeleteMileStone = () => {
    dispatch(deleteMileStoneInProduct(rowItem?.id))
      .then((resp) => {
        if (resp.meta.requestStatus === "fulfilled") {
          addToast({
            title: "Milestone deleted successfully !.",
            color: "success",
          });

          dispatch(
            getProductMileStonesListByProductId({
              userId,
              productId: solutionId,
            }),
          );

          setRowItem(null);
          deleteModal.onClose();
        } else {
          addToast({ title: "Something went wrong !.", color: "danger" });
        }
      })
      .catch(() => {
        addToast({ title: "Something went wrong !.", color: "danger" });
      });
  };

  const renderCell = React.useCallback(
    (rowData, columnKey) => {
      const cellValue = rowData[columnKey];

      switch (columnKey) {
        case "milestoneName":
          return <p className="text-[12.5px]">{rowData?.milestoneName}</p>;

        case "tatInDays":
          return <p className="text-[12.5px]">{rowData?.tatInDays} days</p>;

        case "rollbackTatInDays":
          return (
            <p className="text-[12.5px]">{rowData?.rollbackTatInDays} days</p>
          );

        case "strictApproval":
          return (
            <p className="text-[12.5px]">
              {rowData?.strictApproval ? "YES" : "NO"}
            </p>
          );

        case "mandatory":
          return (
            <p className="text-[12.5px]">{rowData?.mandatory ? "YES" : "NO"}</p>
          );

        case "autoGenerated":
          return (
            <p className="text-[12.5px]">
              {rowData?.autoGenerated ? "YES" : "NO"}
            </p>
          );

        case "allowRollback":
          return (
            <p className="text-[12.5px]">
              {rowData?.allowRollback ? "YES" : "NO"}
            </p>
          );

        case "actions":
          return (
            <div className="relative flex items-center justify-center gap-2">
              <Dropdown>
                <DropdownTrigger>
                  <Button isIconOnly size="sm" variant="light">
                    <EllipsisVertical className="w-4 h-4 text-default-300" />
                  </Button>
                </DropdownTrigger>

                <DropdownMenu>
                  <DropdownItem
                    key="edit"
                    onPress={() => handleActionsPress("edit", rowData)}
                  >
                    Edit
                  </DropdownItem>

                  <DropdownItem
                    key="delete"
                    color="danger"
                    onPress={() => handleActionsPress("delete", rowData)}
                  >
                    Delete
                  </DropdownItem>
                </DropdownMenu>
              </Dropdown>
            </div>
          );

        default:
          return cellValue;
      }
    },
    [handleActionsPress],
  );

  const onSearchChange = React.useCallback((value) => {
    setFilterValue(value || "");
  }, []);

  const onClear = React.useCallback(() => {
    setFilterValue("");
  }, []);

  const buildPayload = (values) => {
    return {
      productId: toNumber(solutionId),
      milestoneId: toNumber(values.milestoneId),

      order: toNumber(values.order),
      tatInDays: toNumber(values.tatInDays),

      executionTatApplicable: values.executionTatApplicable,
      executionTatInDays: toNumber(values.executionTatInDays),
      executionTatHours: toNumber(values.executionTatHours),

      departmentTatApplicable: values.departmentTatApplicable,
      departmentTatHours: toNumber(values.departmentTatHours),

      performanceTatApplicable: values.performanceTatApplicable,
      performanceTatHours: toNumber(values.performanceTatHours),

      customerTatApplicable: values.customerTatApplicable,
      customerTatHours: toNumber(values.customerTatHours),

      rollbackTatApplicable: values.rollbackTatApplicable,
      rollbackTatInDays: toNumber(values.rollbackTatInDays),
      rollbackTatHours: toNumber(values.rollbackTatHours),

      strictApproval: values.strictApproval,
      allowRollback: values.allowRollback,

      maxAttempts: toNumber(values.maxAttempts),
      paymentPercentage: toNumber(values.paymentPercentage),

      requiresPortalDetails: values.requiresPortalDetails,
      allowTatResetOnReassign: values.allowTatResetOnReassign,
      businessDaysEnabled: values.businessDaysEnabled,

      reminderBeforeDueHours: toNumber(values.reminderBeforeDueHours),
      managerEscalationAfterDueHours: toNumber(
        values.managerEscalationAfterDueHours,
      ),
      hodEscalationAfterDueHours: toNumber(values.hodEscalationAfterDueHours),

      mandatory: values.mandatory,
      active: values.active,
      autoGenerated: values.autoGenerated,

      rollbackTatValid: true,
      customerTatValid: true,
      departmentTatValid: true,
      performanceTatValid: true,
      executionTatValid: true,
    };
  };

  const onSubmit = useCallback(
    (values) => {
      const obj = buildPayload(values);

      if (rowItem) {
        dispatch(updateMilestoneInProduct({ id: rowItem?.id, data: obj }))
          .then((resp) => {
            if (resp.meta.requestStatus === "fulfilled") {
              addToast({
                title: "Milestone updated successfully !.",
                color: "success",
              });

              dispatch(
                getProductMileStonesListByProductId({
                  userId,
                  productId: solutionId,
                }),
              );

              onClose();
              setRowItem(null);
              reset(defaultValues);
            } else {
              addToast({
                title: resp.payload?.data?.errorCode || "ERROR",
                description:
                  resp.payload?.data?.message ||
                  resp.payload?.message ||
                  "Milestone update failed.",
                color: "danger",
              });
            }
          })
          .catch(() =>
            addToast({ title: "Something went wrong !.", color: "danger" }),
          );
      } else {
        dispatch(addMileStoneInProduct(obj))
          .then((resp) => {
            if (resp.meta.requestStatus === "fulfilled") {
              addToast({
                title: "Milestone mapped with product successfully !.",
                color: "success",
              });

              dispatch(
                getProductMileStonesListByProductId({
                  userId,
                  productId: solutionId,
                }),
              );

              onClose();
              setRowItem(null);
              reset(defaultValues);
            } else {
              addToast({
                title: resp.payload?.data?.errorCode || "ERROR",
                description:
                  resp.payload?.data?.message ||
                  resp.payload?.message ||
                  "Milestone mapping failed.",
                color: "danger",
              });
            }
          })
          .catch(() =>
            addToast({ title: "Something went wrong !.", color: "danger" }),
          );
      }
    },
    [dispatch, onClose, reset, userId, solutionId, rowItem],
  );

  const topContent = React.useMemo(() => {
    return (
      <div className="flex flex-col gap-2">
        <div className="flex justify-between gap-2 items-center flex-wrap">
          <Input
            isClearable
            size="sm"
            className="w-full sm:max-w-[280px]"
            classNames={{ inputWrapper: "h-8 min-h-8" }}
            placeholder="Search..."
            startContent={<Search className="w-4 h-4 text-default-400" />}
            value={filterValue}
            onClear={onClear}
            onValueChange={onSearchChange}
          />

          <div className="flex gap-1.5 flex-wrap">
            <Button
              size="sm"
              endContent={<Plus className="w-3.5 h-3.5" />}
              color="primary"
              onPress={handleOpenAddModal}
            >
              Map milestone
            </Button>

            <Dropdown>
              <DropdownTrigger>
                <Button
                  size="sm"
                  variant="flat"
                  endContent={<ChevronDown className="w-3.5 h-3.5" />}
                >
                  Columns
                </Button>
              </DropdownTrigger>

              <DropdownMenu
                disallowEmptySelection
                aria-label="Table Columns"
                closeOnSelect={false}
                selectedKeys={visibleColumns}
                selectionMode="multiple"
                onSelectionChange={setVisibleColumns}
              >
                {columns.map((column) => (
                  <DropdownItem key={column.uid} className="capitalize">
                    {capitalize(column.name)}
                  </DropdownItem>
                ))}
              </DropdownMenu>
            </Dropdown>
          </div>
        </div>

        <div className="flex justify-between items-center">
          <span className="text-default-400 text-[12.5px]">
            Total {sortedItems.length} milestones
          </span>
        </div>
      </div>
    );
  }, [
    filterValue,
    visibleColumns,
    onSearchChange,
    onClear,
    sortedItems.length,
  ]);

  return (
    <div className="flex flex-col gap-2">
      <h1 className="font-sans text-lg font-semibold mb-2 shrink-0">
        Milestones list
      </h1>

      <Table
        isHeaderSticky
        removeWrapper={false}
        aria-label="Product milestone table"
        bottomContentPlacement="outside"
        classNames={{
          base: "gap-2.5",
          wrapper:
            "max-h-[calc(100vh-320px)] w-full overflow-y-auto rounded-lg border border-gray-200 dark:border-white/10 shadow-none p-0",
          table: "w-full",
          thead: "[&>tr]:first:rounded-none",
          th: "h-8 py-0 text-[11.5px] tracking-wide bg-gray-50 dark:bg-neutral-900 text-default-500 first:rounded-none last:rounded-none border-b border-gray-200 dark:border-white/10",
          td: "py-1.5 text-[12.5px]",
        }}
        sortDescriptor={sortDescriptor}
        topContent={topContent}
        topContentPlacement="outside"
        onSortChange={setSortDescriptor}
      >
        <TableHeader columns={headerColumns}>
          {(column) => (
            <TableColumn
              key={column.uid}
              align={column.uid === "actions" ? "center" : "start"}
              allowsSorting={column.sortable}
            >
              {column.name}
            </TableColumn>
          )}
        </TableHeader>

        <TableBody emptyContent={"No data found"} items={sortedItems}>
          {(item) => (
            <TableRow key={item.id}>
              {(columnKey) => (
                <TableCell>{renderCell(item, columnKey)}</TableCell>
              )}
            </TableRow>
          )}
        </TableBody>
      </Table>

      <Modal
        size="5xl"
        isDismissable={false}
        isKeyboardDismissDisabled={true}
        isOpen={isOpen}
        onOpenChange={onOpenChange}
        placement="top-center"
        scrollBehavior="inside"
      >
        <ModalContent>
          {(onClose) => (
            <>
              <ModalHeader>
                {rowItem ? "Update milestone" : "Add Milestone"}
              </ModalHeader>

              <ModalBody>
                <form onSubmit={handleSubmit(onSubmit)}>
                  <div className="grid max-h-[65vh] grid-cols-1 gap-4 overflow-auto md:grid-cols-2 lg:grid-cols-3">
                    <Controller
                      name="milestoneId"
                      control={control}
                      render={({ field, fieldState: { error } }) => (
                        <NewSelect
                          isRequired={true}
                          data={mileStoneList || []}
                          label={"Select milestone"}
                          name={"milestoneId"}
                          labelKey={"name"}
                          valueKey={"id"}
                          value={field.value}
                          onChange={(selectedSet) => {
                            field.onChange(selectedSet);
                          }}
                          errorMessage={error?.message}
                          isInvalid={!!error}
                        />
                      )}
                    />

                    {renderNumberInput("order", "Order")}
                    {renderNumberInput("tatInDays", "TAT (in days)")}

                    {renderBooleanSelect(
                      "executionTatApplicable",
                      "Execution TAT applicable",
                    )}
                    {renderNumberInput(
                      "executionTatInDays",
                      "Execution TAT (in days)",
                    )}
                    {renderNumberInput(
                      "executionTatHours",
                      "Execution TAT hours",
                    )}

                    {renderBooleanSelect(
                      "departmentTatApplicable",
                      "Department TAT applicable",
                    )}
                    {renderNumberInput(
                      "departmentTatHours",
                      "Department TAT hours",
                    )}

                    {renderBooleanSelect(
                      "performanceTatApplicable",
                      "Performance TAT applicable",
                    )}
                    {renderNumberInput(
                      "performanceTatHours",
                      "Performance TAT hours",
                    )}

                    {renderBooleanSelect(
                      "customerTatApplicable",
                      "Customer TAT applicable",
                    )}
                    {renderNumberInput(
                      "customerTatHours",
                      "Customer TAT hours",
                    )}

                    {renderBooleanSelect(
                      "rollbackTatApplicable",
                      "Rollback TAT applicable",
                    )}
                    {renderNumberInput(
                      "rollbackTatInDays",
                      "Rollback TAT (in days)",
                    )}
                    {renderNumberInput(
                      "rollbackTatHours",
                      "Rollback TAT hours",
                    )}

                    {renderBooleanSelect("strictApproval", "Strict approval")}
                    {renderBooleanSelect("allowRollback", "Allow rollback")}

                    {renderNumberInput("maxAttempts", "Max attempts")}
                    {renderNumberInput(
                      "paymentPercentage",
                      "Payment percentage",
                    )}

                    {renderBooleanSelect(
                      "requiresPortalDetails",
                      "Requires portal details",
                    )}
                    {renderBooleanSelect(
                      "allowTatResetOnReassign",
                      "Allow TAT reset on reassign",
                    )}
                    {renderBooleanSelect(
                      "businessDaysEnabled",
                      "Business days enabled",
                    )}

                    {renderNumberInput(
                      "reminderBeforeDueHours",
                      "Reminder before due hours",
                    )}
                    {renderNumberInput(
                      "managerEscalationAfterDueHours",
                      "Manager escalation after due hours",
                    )}
                    {renderNumberInput(
                      "hodEscalationAfterDueHours",
                      "HOD escalation after due hours",
                    )}

                    {renderBooleanSelect("mandatory", "Mandatory")}
                    {renderBooleanSelect("active", "Active")}
                    {renderBooleanSelect("autoGenerated", "Auto generated")}
                  </div>

                  <ModalFooter className="flex justify-end">
                    <Button onPress={onClose}>Cancel</Button>
                    <Button color="primary" type="submit">
                      Submit
                    </Button>
                  </ModalFooter>
                </form>
              </ModalBody>
            </>
          )}
        </ModalContent>
      </Modal>

      <Modal
        isOpen={deleteModal.isOpen}
        onOpenChange={deleteModal.onOpenChange}
        backdrop="blur"
      >
        <ModalContent>
          {(onClose) => (
            <>
              <ModalHeader className="flex flex-col gap-1">Delete</ModalHeader>

              <ModalBody>
                <p>Are you sure to delete this item ?</p>
              </ModalBody>

              <ModalFooter>
                <Button onPress={onClose}>No</Button>
                <Button color="primary" onPress={handleDeleteMileStone}>
                  Yes
                </Button>
              </ModalFooter>
            </>
          )}
        </ModalContent>
      </Modal>
    </div>
  );
};

export default ProductMilestones;
